export enum VerificationMethod {
    LICENSE_VERIFICATION = 'LICENSE_VERIFICATION',
    WORK_EMAIL_VERIFICATION = 'WORK_EMAIL_VERIFICATION',
    PRIVATE_CERTIFICATE_UPLOAD = 'PRIVATE_CERTIFICATE_UPLOAD',
    MANUAL_REVIEW = 'MANUAL_REVIEW',
  }